### ISSUE TITLE
Bug: Runner Availability does not persist once the page is left

### ISSUE THREAD

**Issue by EpicYoshiMaster** [Corvimae/split-decision#1]
Reproduce Steps:
1. Go to your Submission page for a Marathon, and select some availability times
2. Select Return to my profile
3. Go back to the Submission page

Result: Availability times are reset and not saved.
Expected: Availability times are saved from previous selection.

This happens regardless of if you save games for the submission in the same session.

**Comment by Corvimae** [comment]
Fixed.
